"use client";

import { useEffect, useRef, useState } from "react";
import type { Decision } from "@/lib/decision-engine";

const KIND_COLOR: Record<Decision["kind"], string> = {
  rebalance: "text-fg",
  claim: "text-warn",
  open: "text-human",
  close: "text-ai",
  hold: "text-faint",
};

const KIND_LABEL: Record<Decision["kind"], string> = {
  rebalance: "REBAL",
  claim: "CLAIM",
  open: "OPEN",
  close: "CLOSE",
  hold: "HOLD",
};

function relTime(seconds: number): string {
  const now = Date.now() / 1000;
  const diff = Math.max(0, now - seconds);
  if (diff < 60) return `${Math.floor(diff)}s`;
  if (diff < 3600) return `${Math.floor(diff / 60)}m`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h`;
  return `${Math.floor(diff / 86400)}d`;
}

export function DecisionFeed({
  duelId,
  variant = "duel",
}: {
  duelId?: string;
  variant?: "duel" | "global";
}) {
  const [items, setItems] = useState<Decision[]>([]);
  const [live, setLive] = useState(false);
  const seen = useRef(new Set<string>());

  useEffect(() => {
    const url = duelId ? `/api/decisions/stream?duelId=${duelId}` : "/api/decisions/stream";
    const es = new EventSource(url);

    es.addEventListener("hello", () => setLive(true));
    es.addEventListener("decision", (ev) => {
      try {
        const d = JSON.parse((ev as MessageEvent).data) as Decision;
        if (seen.current.has(d.id)) return;
        seen.current.add(d.id);
        setItems((prev) => [d, ...prev].slice(0, 40));
      } catch {}
    });
    es.onerror = () => setLive(false);

    return () => {
      es.close();
    };
  }, [duelId]);

  if (items.length === 0) {
    return (
      <div className="surface p-6 text-[13px] text-dim">
        <div className="mono text-[10px] mb-2 flex items-center gap-1.5">
          <span className={`h-1.5 w-1.5 rounded-full ${live ? "bg-profit animate-pulse" : "bg-[var(--color-border-strong)]"}`} />
          {live ? "CONNECTED" : "CONNECTING…"}
        </div>
        Waiting for the next agent decision…
      </div>
    );
  }

  return (
    <div className="surface divide-y divide-[var(--color-border)]">
      <div className="px-4 py-2.5 flex items-center justify-between text-[10px] mono tracking-wider">
        <span className={`flex items-center gap-1.5 ${live ? "text-profit" : "text-faint"}`}>
          <span className={`h-1.5 w-1.5 rounded-full ${live ? "bg-profit animate-pulse" : "bg-[var(--color-border-strong)]"}`} />
          {live ? "LIVE FEED" : "DISCONNECTED"}
        </span>
        <span className="text-faint normal-case tracking-normal">streamed via SSE · logged on-chain</span>
      </div>
      {items.map((d) => (
        <div key={d.id} className="px-4 py-3 flex items-start gap-3 text-[13px]">
          <span className="mono text-[10px] text-faint w-10 pt-0.5 shrink-0">{relTime(d.at)} ago</span>
          <span
            className={`mono text-[10px] w-12 pt-1 shrink-0 font-semibold tracking-wider ${KIND_COLOR[d.kind]}`}
          >
            {KIND_LABEL[d.kind]}
          </span>
          <span
            className={`mono text-[11px] ${d.agentSide === "A" ? "text-human" : "text-ai"} w-20 pt-0.5 shrink-0`}
          >
            {d.agentName}
          </span>
          <span className="text-fg/90 flex-1 leading-relaxed">
            {d.text}
            {d.llm && (
              <span
                className="ml-2 mono text-[9px] text-warn px-1 py-0.5 rounded border border-warn/30 align-middle"
                title="generated by Gemini 2.5 Flash"
              >
                GEMINI
              </span>
            )}
            {variant === "global" && (
              <span className="ml-2 text-faint mono text-[10px]">→ {d.duelId}</span>
            )}
          </span>
          {d.txHash && (
            <span className="mono text-[10px] text-faint shrink-0 pt-1 hidden sm:inline">
              {d.txHash.slice(0, 6)}…{d.txHash.slice(-4)}
            </span>
          )}
        </div>
      ))}
    </div>
  );
}
