"use client";

import { useEffect, useRef, useState } from "react";
import type { Decision } from "@/lib/decision-engine";

const KIND_TINT: Record<Decision["kind"], { color: string; bg: string }> = {
  rebalance: { color: "var(--vs-ink)",       bg: "var(--vs-cream)" },
  claim:     { color: "var(--vs-ochre-deep)", bg: "var(--vs-ochre-soft)" },
  open:      { color: "var(--vs-machine-deep)", bg: "var(--vs-machine-wash)" },
  close:     { color: "var(--vs-human-deep)",   bg: "var(--vs-human-wash)" },
  hold:      { color: "var(--vs-ink-3)",      bg: "var(--vs-cream)" },
};

const KIND_LABEL: Record<Decision["kind"], string> = {
  rebalance: "REBAL",
  claim: "CLAIM",
  open: "OPEN",
  close: "CLOSE",
  hold: "HOLD",
};

function relTime(seconds: number): string {
  const now = Date.now() / 1000;
  const diff = Math.max(0, now - seconds);
  if (diff < 60) return `${Math.floor(diff)}s`;
  if (diff < 3600) return `${Math.floor(diff / 60)}m`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h`;
  return `${Math.floor(diff / 86400)}d`;
}

export function DecisionFeed({
  duelId,
  variant = "duel",
}: {
  duelId?: string;
  variant?: "duel" | "global";
}) {
  const [items, setItems] = useState<Decision[]>([]);
  const [live, setLive] = useState(false);
  const seen = useRef(new Set<string>());

  useEffect(() => {
    const url = duelId ? `/api/decisions/stream?duelId=${duelId}` : "/api/decisions/stream";
    const es = new EventSource(url);

    es.addEventListener("hello", () => setLive(true));
    es.addEventListener("decision", (ev) => {
      try {
        const d = JSON.parse((ev as MessageEvent).data) as Decision;
        if (seen.current.has(d.id)) return;
        seen.current.add(d.id);
        setItems((prev) => [d, ...prev].slice(0, 40));
      } catch {}
    });
    es.onerror = () => setLive(false);

    return () => {
      es.close();
    };
  }, [duelId]);

  if (items.length === 0) {
    return (
      <div className="surface-paper p-6 text-[13px] text-ink-2">
        <div className="mono text-[10px] mb-2 flex items-center gap-1.5 eyebrow">
          <span
            className="h-1.5 w-1.5 rounded-full"
            style={{
              background: live ? "var(--vs-positive)" : "var(--vs-line-2)",
              animation: live ? "pulse-soft 2.4s ease-in-out infinite" : undefined,
            }}
          />
          {live ? "Connected" : "Connecting…"}
        </div>
        Waiting for the next agent decision…
      </div>
    );
  }

  return (
    <div className="surface-paper divide-y divide-line overflow-hidden">
      <div className="px-5 py-3 flex items-center justify-between">
        <span className="eyebrow inline-flex items-center gap-1.5">
          <span
            className="h-1.5 w-1.5 rounded-full"
            style={{
              background: live ? "var(--vs-positive)" : "var(--vs-line-2)",
              animation: live ? "pulse-soft 2.4s ease-in-out infinite" : undefined,
            }}
          />
          {live ? "Live feed" : "Disconnected"}
        </span>
        <span className="text-caption">Streamed via SSE · logged on-chain</span>
      </div>
      {items.map((d) => {
        const tint = KIND_TINT[d.kind];
        return (
          <div key={d.id} className="px-5 py-3 flex items-start gap-3 text-[14px]">
            <span className="mono text-[12px] text-ink-3 w-12 pt-1 shrink-0">{relTime(d.at)} ago</span>
            <span
              className="mono text-[11px] font-semibold tracking-wider px-2 py-1 rounded-md shrink-0"
              style={{ color: tint.color, background: tint.bg }}
            >
              {KIND_LABEL[d.kind]}
            </span>
            <span className="mono text-[12.5px] w-20 pt-1 shrink-0 font-semibold" style={{ color: "var(--vs-machine-deep)" }}>
              {d.agentName}
            </span>
            <span className="text-ink-2 flex-1 leading-relaxed">
              {d.text}
              {d.llm && (
                <span
                  className="ml-2 mono text-[10px] font-semibold px-1.5 py-0.5 rounded-md align-middle"
                  style={{ color: "var(--vs-ochre-deep)", background: "var(--vs-ochre-soft)" }}
                  title="generated by Gemini 2.5 Flash"
                >
                  GEMINI
                </span>
              )}
              {variant === "global" && (
                <span className="ml-2 text-ink-3 mono text-[11px]">→ {d.duelId}</span>
              )}
            </span>
            {d.txHash && (
              <span className="mono text-[11px] text-ink-3 shrink-0 pt-1 hidden sm:inline">
                {d.txHash.slice(0, 6)}…{d.txHash.slice(-4)}
              </span>
            )}
          </div>
        );
      })}
    </div>
  );
}
